In [10]:
import numpy as np


In [11]:
#1. Create a null vector of size 10 but the fifth value which is 1.

arr = np.zeros(10)
print(f"Null vetor of 10: {arr}")

arr[5] = 1
print(f"adding 1 at 5th position: {arr}")

Null vetor of 10: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
adding 1 at 5th position: [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


In [16]:
#2. Create a vector with values ranging from 10 to 49.

arr1 = np.random.randint(10,50,10)
print(arr1)


[22 27 21 25 43 39 34 46 29 45]


In [18]:
#3. Create a 3x3 matrix with values ranging from 0 to 8
arr2 = np.random.randint(0,9,[3,3])
print(arr2)


[[6 2 2]
 [1 3 3]
 [3 4 5]]


In [31]:
#4. Find indices of non-zero elements from [1,2,0,0,4,0]
arr3 = np.array([1,2,0,0,4,0])
print(arr3)

np.nonzero(arr3)

[1 2 0 0 4 0]


(array([0, 1, 4], dtype=int64),)

In [21]:
#5. Create a 10x10 array with random values and find the minimum and maximum values.

np.random.seed(101)
arr4 = np.random.randint(0,25,[10,10])
print(arr4)

#max and min vlaues
max_val = arr4.max()
min_val = arr4.min()
print(f"Maximum value in the vector is {max_val}")
print(f"Minimum value in the vector is {min_val}")

[[11 17  6 23 11 15  9 13  8  4]
 [ 8 21  0 14  5 12  8 17 19 15]
 [ 8 19 19  2 12  8 19 10 12 11]
 [23  0  9 23  9 15  8  4 19  3]
 [ 7 10 20 24  7  6 14  9 20 18]
 [23  7  7 15 12  0 20 10 12 17]
 [24 11 19 15  1 24  4 19 18  3]
 [10 19  7 20  8 22 19 23 14 15]
 [22  5 22  9 13  2 18 15 11 10]
 [17  3  3 19 20 15 14  5  5 24]]
Maximum value in the array is 24
Minimum value in the array is 0


In [29]:
#6. Create a random vector of size 30 and find the mean value.
arr5 = np.random.randint(0,26,30)
print(arr5)

#mean
mean_val = arr5.mean()
print(f"Mean of vector is {round(mean_val,3)}")

[18  7  3  2 12 25 23 20  5 21  9  2 22  5 21 24 25 14 10 11  1  9 11 20
 18  3 14 15 16 17]
Mean of vector is 13.433
